server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/merchant_pipe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: NewStrongPass!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: MYSQL
  flyway:
    enabled: true
    locations: filesystem:../database
  redis:
    host: localhost
    port: 6379
    password: ""

pipe:
  trigger:
    autoSchedule: true
    markServerAddress: false
    timeoutSeconds: 172800
